# Generated by Django 5.2 on 2025-04-16 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_booking_booking_date_booking_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='datein',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dateout',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_attendees',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
