# Generated by Django 5.2 on 2025-04-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_booking_room_remove_booking_datein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
