# Generated by Django 5.2 on 2025-04-16 11:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_attendees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
