# Generated by Django 5.1.7 on 2025-05-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('ATTENDED', 'Attended'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
